In [128]:
import torch
import torch.nn as nn
import numpy as np 
import random
import torch.optim as optim

In [211]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print(device)

cuda


In [90]:
x_val = [i for i in range(20)]
x_val

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [238]:
y_val = [2*i + 1 + random.randint(1,100)*0.01 for i in x_val]
y_val

[1.6800000000000002,
 3.48,
 5.83,
 7.65,
 9.92,
 11.64,
 13.34,
 15.24,
 17.03,
 19.92,
 21.03,
 23.61,
 25.36,
 27.65,
 29.74,
 31.32,
 33.3,
 35.57,
 37.38,
 39.69]

In [240]:
x_train = np.array(x_val, dtype=np.float32) 
x_train = x_train.reshape(-1,1) 
y_train = np.array(y_val, dtype=np.float32)
y_train = y_train.reshape(-1,1)

In [242]:
class LinearRegModel(nn.Module):
    def __init__(self):
        super(LinearRegModel,self).__init__()
        self.linear = nn.Linear(1,1)

    def forward(self, x):
        return self.linear(x)

In [244]:
model = LinearRegModel()
model

LinearRegModel(
  (linear): Linear(in_features=1, out_features=1, bias=True)
)

In [246]:
loss_fc = nn.MSELoss()
optimizer = optim.SGD(model.parameters(),lr=0.001) 


In [248]:
epochs = 1000
for epoch in range(epochs): 
    model.train() 
    in_val = torch.from_numpy(x_train) 
    labels = torch.from_numpy(y_train) 
    pre_spreed = model(in_val) 
    loss = loss_fc(pre_spreed,labels) 
    optimizer.zero_grad() 
    loss.backward()
    optimizer.step()

    if (epoch+1)%100 == 0 : 
        print(f'Epoch:[{epoch+1}/{epochs}],loss:[{loss.item()}]')
    

Epoch:[100/1000],loss:[1.3589826822280884]
Epoch:[200/1000],loss:[1.2273198366165161]
Epoch:[300/1000],loss:[1.1090272665023804]
Epoch:[400/1000],loss:[1.0027480125427246]
Epoch:[500/1000],loss:[0.9072619676589966]
Epoch:[600/1000],loss:[0.8214724659919739]
Epoch:[700/1000],loss:[0.7443949580192566]
Epoch:[800/1000],loss:[0.6751445531845093]
Epoch:[900/1000],loss:[0.612927258014679]
Epoch:[1000/1000],loss:[0.5570272207260132]


In [249]:
model.eval()

predicted = model(torch.from_numpy(x_train).requires_grad_())
predicted

tensor([[ 0.2504],
        [ 2.3458],
        [ 4.4412],
        [ 6.5365],
        [ 8.6319],
        [10.7273],
        [12.8226],
        [14.9180],
        [17.0134],
        [19.1088],
        [21.2041],
        [23.2995],
        [25.3949],
        [27.4903],
        [29.5856],
        [31.6810],
        [33.7764],
        [35.8718],
        [37.9671],
        [40.0625]], grad_fn=<AddmmBackward0>)

In [250]:
torch.save(model.state_dict(),'model.pkl')

In [254]:
model.load_state_dict(torch.load('model.pkl'))

<All keys matched successfully>

In [256]:
new_val = [i for i in range(20,40)]
new_val

[20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39]

In [258]:
new_input = np.array(new_val,dtype=np.float32)
new_input = new_input.reshape(-1,1)
new_input = torch.from_numpy(new_input) 
new_input

tensor([[20.],
        [21.],
        [22.],
        [23.],
        [24.],
        [25.],
        [26.],
        [27.],
        [28.],
        [29.],
        [30.],
        [31.],
        [32.],
        [33.],
        [34.],
        [35.],
        [36.],
        [37.],
        [38.],
        [39.]])

In [260]:
new_predicted = model(new_input) 
new_predicted

tensor([[42.1579],
        [44.2532],
        [46.3486],
        [48.4440],
        [50.5394],
        [52.6347],
        [54.7301],
        [56.8255],
        [58.9209],
        [61.0162],
        [63.1116],
        [65.2070],
        [67.3023],
        [69.3977],
        [71.4931],
        [73.5885],
        [75.6838],
        [77.7792],
        [79.8746],
        [81.9700]], grad_fn=<AddmmBackward0>)